### ISSUE TITLE
Add a faq page explaining the  personal data policy of data.gouv.fr

### ISSUE THREAD

**Issue by odtvince** [etalab/udata-gouvfr#135]
Quelques demandes de retraits de données personnelles dans des fichiers référencés sur data.gouv arrivent parfois sur contact@ plutôt que chez le producteur ou le réutilisateur.

Il serait opportun d'ajouter une page de FAQ pédagogique expliquant que:

1. data.gouv n'est pas l'éditeur de ces sites ou fichiers
2. que les données utilisées par ces sites sont issues de données publiques, avec des textes prévoyant leur publication (parfois même obligatoire)
3. que leur réutilisation par les sites en question peut éventuellement nécessiter une déclaration auprès de la CNIL
4. ...que si c'est le cas, toute réclamation doit être effectuée directement auprès du site en question

autre chose ?

**Comment by abulte** [comment]
I think https://www.data.gouv.fr/fr/terms/ and https://www.data.gouv.fr/fr/suivi handle this.
