### ISSUE TITLE
Missing translation for search results

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/udata-gouvfr#146]
<img width="475" alt="capture d ecran 2017-01-12 a 15 47 32" src="https://cloud.githubusercontent.com/assets/1231232/21894189/8a484cc8-d8de-11e6-9f6f-bf7dc831f692.png">

No need to explain ;)
With maybe a small CSS adjustment.

**Comment by noirbizarre** [comment]
Yes, already fixed on next version ;)
