### ISSUE TITLE
Ability to filter on badges

### ISSUE THREAD

**Issue by cecilaki** [etalab/udata-gouvfr#162]
Would be super useful to use the time filters on badges. Would it be hard to be implemented ? 
Ex : I would like to filter by year & months some datasets that are under a certain tag. How can I do that ?

**Comment by noirbizarre** [comment]
Hi, this is already possible:
You can use the time range facet to choose your time filter and then the badge facet to choose the badge.

In a query string (for both the search interface and the API), this will look like: `datasets/?badge=my-badge&temporal_coverage=2010-01-01-2015-12-31`

You can to do the same thing with tags: `datasets/?tag=tag-1&tag=tag-2&temporal_coverage=2010-01-01-2015-12-31`

In fact you can combine any filterable facet and also use the `OR` operator (`|`), so to list datasets with data between **2010/01/01** and **2015/12/31** having **my-badge** badge and having **tag-1** or **tag-2** tag you can write:
```
datasets/?badge=my-badge&tag=tag-1|tag-2&temporal_coverage=2010-01-01-2015-12-31
```

**Comment by cecilaki** [comment]
Thanks @noirbizarre very good to know !

**Comment by noirbizarre** [comment]
You're welcome ;)
