### ISSUE TITLE
uData API /spatial/coverage/{level} with {zone}

### ISSUE THREAD

**Issue by GrondinDam** [etalab/udata-gouvfr#173]
Bonjour, 

Est-il possible d'obtenir la même chose que l'on obtient avec l'API en utilisant 
```
/spatial/coverage/{level}
```
Mais en spécifiant cette fois une {zone} à la place d'un {level}

Actuellement si je met dans l'API
```
/spatial/coverage/fr/town
```
L'API va parcourir toutes les villes possible et va déboucher sur un "504 Gateway Time-out"

Moi ce que j'aimerai faire c'est quelque chose du style : 
```
/spatial/coverage/fr/town/97414
```
Est il déjà possible de le faire ? (il est possible que j'ai raté la feature)
Ou alors est ce en cours d'implémentation ?

Merci

**Comment by noirbizarre** [comment]
Bonjour,
L'API `/spatial/coverage` est totalement expérimentale et peu optimisée. Il n'est pas aujourd'hui possible d'effectuer cette opération, mais je note l'idée.

Par contre vous pouvez déjà effectuer une recherche par zone pour obtenir la liste des jeux de données associés: `/datasets/?geozone=fr/town/97414`

Il doit être possible de construire un résultat similaire avec des appels à:
- `/spatial/zone/{id}/children` pour lister les zones enfants (avec leur geométrie)
- `/spatial/zone/{id}` pour accéder à la géométrie et au détails d'une zone particulière

**Comment by davidbgk** [comment]
Attention, les ids geozones vont changer à la suite du merge de https://github.com/opendatateam/udata/pull/501

**Comment by GrondinDam** [comment]
Merci pour vos réponses.

Je voulais passer par ```/spatial/coverage``` car elle donne directement le nombre de datasets par zone sans pour autant récupérer tous les jeux de données.

En effet, au final je suis passé par ```/spatial/zone/{id}/datasets``` pour avoir tous les jeux de données d'une zone et ensuite les compter.

Cela m'oblige à récupérer tous les jeux de données d'une zone. Mais bon au final ce n'est qu'une question d'optimisation. 

Encore merci.

Cordialement
