### ISSUE TITLE
Old code region in data.gouv

### ISSUE THREAD

**Issue by GrondinDam** [etalab/udata-gouvfr#175]
Bonjour, 

Je travaille actuellement sur la réalisation d'une intéropérabilité entre data.gouv et communecter.org

J'intégre les jeux de données de data.gouv en les filtrant par {zone} comme : https://www.data.gouv.fr/fr/territory/county/974/

Cependant en intégrant les jeux de données des régions, je me suis rendu compte que le nom des régions et leurs code correspondaient aux anciennes régions (d'avant la réforme territorial de 2016).

Exemple : 

La région 73 de data.gouv : https://www.data.gouv.fr/fr/territory/region/73/ correspond à l'ancienne région Midi-Pyrénées.

Or cette région n'existe plus : la nouvelle région se nomme Occitanie et à pour code 76.

L'implémentation des nouvelles régions est il à l'ordre du jour pour data.gouv ? 

Cordialement.

**Comment by davidbgk** [comment]
Bonjour @GrondinDam,

Oui il s'agit d'un travail en cours de développement actif avec la réalisation de [GeoHisto](https://github.com/etalab/geohisto), son intégration dans [GeoZones](https://github.com/etalab/geozones/pull/22) puis sont inclusion dans [udata](https://github.com/opendatateam/udata/pull/501) et [udata-gouvfr](https://github.com/etalab/udata-gouvfr/pull/116).

Ça devrait arriver sous peu.

**Comment by GrondinDam** [comment]
Merci pour votre réponse. 

J'en prend note. 
J'ai hâte que ce travail soit fait afin de pouvoir completer mon travail sur les régions. :)

Bon courage pour la suite.

Cordialement
