### ISSUE TITLE
Problem with "build assets"

### ISSUE THREAD

**Issue by ChrisBarriere** [etalab/udata-gouvfr#179]
I launch inv assets and there's an exception because there's a markdown file in theme/img/ directory

I delete /theme/img/logo-colophon.md and everything is ok

**Comment by oncletom** [comment]
@ChrisBarriere I can't reproduce the problem at the minute when running `inv assets_builds` so I assume it has been fixed. Please reopen the issue if you still encounter the problem after pulling the latest changes from git 🙂
