### ISSUE TITLE
[territories] add blank space under "connect" block

### ISSUE THREAD

**Issue by abulte** [etalab/udata-gouvfr#184]
I think this block deserves a little more blank space underneath, it feels a little cramped as is.

<img width="1225" alt="capture d ecran 2017-06-22 12 46 21" src="https://user-images.githubusercontent.com/119625/27434014-f1d9187e-574e-11e7-9814-138bccec9397.png">

**Comment by oncletom** [comment]
@abulte `.dataset-list` lacks of a `row` className and could benefit of a `margin: 2em 0` (1em is in use for the horizontal spacing of the cells below).

<img width="1278" alt="screen shot 2017-06-22 at 15 57 19" src="https://user-images.githubusercontent.com/138627/27440948-0f005416-5764-11e7-9bd8-bac3c2009819.png">

**Comment by oncletom** [comment]
Other stuff may be addressed by the UX/UI thinking initiated by @thimy 😃

**Comment by oncletom** [comment]
I close this issue as the conversation and resolution are handled upstream in opendatateam/udata#1088.
