### ISSUE TITLE
[proposal] Grid alignments and streamlining sizes

### ISSUE THREAD

**Issue by oncletom** [etalab/udata-gouvfr#186]
# Before

<img width="1192" alt="screen shot 2017-06-22 at 17 42 54" src="https://user-images.githubusercontent.com/138627/27445645-65e4eae0-5772-11e7-9e06-9651279faa3e.png">

# After

![image](https://user-images.githubusercontent.com/138627/27445866-5fd0d29e-5773-11e7-83ef-f244eed8064f.png)

**Comment by davidbgk** [comment]
If we keep Thématiques, we should put the button after the dropdown? (I think we should remove it)

**Comment by davidbgk** [comment]
Idea: putting the Contribuez button within the header and not in the search bar to avoid confusion with the search button.

**Comment by oncletom** [comment]
A bit more spacing in the top nav, plus infinitive tense.

<img width="1171" alt="screen shot 2017-06-22 at 18 09 37" src="https://user-images.githubusercontent.com/138627/27446582-01e1f17e-5776-11e7-96cb-938fe065042d.png">

**Comment by oncletom** [comment]
I close it here as the conversation and resolution are handled upstream in opendatateam/udata#1088

**Comment by abulte** [comment]
Not everything done, but I think we're a little bit better now.

<img width="1204" alt="Capture d'écran 2019-06-11 17 42 39" src="https://user-images.githubusercontent.com/119625/59286607-531ac580-8c70-11e9-883f-8d396d88fa18.png">
