### ISSUE TITLE
La guerre des boutons

### ISSUE THREAD

**Issue by oncletom** [etalab/udata-gouvfr#188]
The `.btn` class is applied to many elements even though the intent does not seem to make look as such.

I have added a border on `.btn` and I feel it impacts too many items.
Buttons also have many form factors and would benefit of being simplified to pave a better signposting.

![image](https://user-images.githubusercontent.com/138627/27489682-5d80b70a-5833-11e7-89ae-5d1f8ce87985.png)

- [x] `.btn-more` is a size different from `.btn-xs` etc.
- [ ] Search button is an icon which would benefit of not being invisible
- [ ] _Contribute_, _Join_, _Follow_ and _Download as CSV_ should be identified as Buttons
- [ ] _X Reuses_, _X Stars_ should (eventually) be links
- [ ] _Edit_ should be an `.btn-xs.btn-default`?

**Comment by noirbizarre** [comment]
The `btn` class is not defined by udata but [by the bootstrap framework](https://getbootstrap.com/docs/3.3/css/#buttons) as base for every/any button (including [button sibling an input field](https://getbootstrap.com/docs/3.3/components/#input-groups-buttons)).
The `btn-xs` class is also defined by the bootstrap framework as a [sizing class](https://getbootstrap.com/docs/3.3/css/#buttons-sizes) (with `btn-sm` and `btn-lg`), including in [the case of input groups](https://getbootstrap.com/docs/3.3/components/#input-groups-sizing)
The `btn-default` is also [defined by the bootstrap framework as basic theming/semantic classes](https://getbootstrap.com/docs/3.3/css/#buttons-options)

The other classes are semantic classes (`btn-more`, `btn-follow`...) defined by udata, allowing to add style to the existing bootstrap ones wihtout breaking the entire styling and should be where customization occurs.
Either there is already a custom class which needs to be customized, either you should add one for the case you want to customize.

In every case, you should avoid modifications on the base bootstrap classes unless:
- this is part of component and needed to fix a sife-effect bug => the style reference should be namespaced (`.my-component .btn`)
- the purpose is to apply a common style on the base bootstrap style (ex. set `btn-default` a given color)

**Note**: There might be some places where styling is misapplied on the base bootstrap classes and this cases require to be fixed.

**Comment by oncletom** [comment]
I did not mean to alter bootstrap base definition of buttons but to apply them where relevant.
I am happy to rephrase to bullet points if they are source of misunderstanding.
