### ISSUE TITLE
Fermeture pop-up partage de jeux de données et intégration

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/udata-gouvfr#199]
Dans la page de description d'un jeu de données lorsque l'on appuie sur le bouton de partage et celui d'intégration la fermeture de la pop-up n'est pas instinctive.
Je propose : 
 - L'intégration d'un bouton close
 - Lors d'un clic en dehors de la pop-up que la pop-up se ferme.

![boutons](https://user-images.githubusercontent.com/2757318/28360890-18d31f32-6c77-11e7-9af9-78773e04dd4d.png)

**Comment by oncletom** [comment]
Je confirme c'est pas évident. Merci d'avoir pris le temps de le signaler 👍

**Comment by abulte** [comment]
No huge tooltips anymore 🎉
