### ISSUE TITLE
Valeur de alt affiche "true" sur l'infobulle du bouton d'intégration d'un jeu de données

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/udata-gouvfr#200]
La valeur de alt sur le bouton d'intégration est `true`.
![true](https://user-images.githubusercontent.com/2757318/28361001-8ddeefea-6c77-11e7-8bc6-ecdde7c9ed6c.png)

**Comment by oncletom** [comment]
Bien vu, merci @l-vincent-l 👍

**Comment by oncletom** [comment]
Je n'arrivais pas à le reproduire en local — c'est réglé sur `next` aka `udata@1.1`.

<img width="179" alt="screen shot 2017-07-26 at 09 25 05" src="https://user-images.githubusercontent.com/138627/28611632-564cffe6-71e4-11e7-9384-87b969df2c12.png">
