### ISSUE TITLE
Superposition des pop-ups

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/udata-gouvfr#201]
Lorsque l'on appuie successivement sur le bouton `partage` puis sur le bouton `intégration` les deux pop-ups se superposent, je pense qu'un bon comportement serait de fermer l'ancienne popup.
![superposition](https://user-images.githubusercontent.com/2757318/28361053-b564ace4-6c77-11e7-923b-e59b9e77137e.png)

**Comment by oncletom** [comment]
Je confirme que ça serait mieux de la manière dont tu le décris.
