### ISSUE TITLE
Les noms de mois ne devraient pas être mis en majuscule

### ISSUE THREAD

**Issue by oncletom** [etalab/udata-gouvfr#206]
![image](https://user-images.githubusercontent.com/138627/28364901-671717a0-6c7e-11e7-8b4d-5267fa5a2fce.png)

C'est le cas pour la date de billet de blog sur la home **mais** ça ne l'est pas dans la colonne de métadonnées d'un dataset _ni_ dans les conversations.

/via @gregoirenovel

**Comment by abulte** [comment]
Plus de billet sur la home
