### ISSUE TITLE
Quelle est la bonne orthographe pour "moissonneur"/"moissoneur" ?

### ISSUE THREAD

**Issue by oncletom** [etalab/udata-gouvfr#208]
Vu sur https://www.data.gouv.fr/fr/admin/harvester/new/

![image](https://user-images.githubusercontent.com/138627/28532019-68da637e-7090-11e7-8a03-3c017a5caf89.png)

Par ailleurs j'aimerais apprendre à corriger/ajouter des traductions donc preneur d'une session en pair pour apprendre à naviguer dans Transifex par la même occasion.

Idem sur https://www.data.gouv.fr/fr/admin/me/

![image](https://user-images.githubusercontent.com/138627/28532273-44d398b4-7091-11e7-9d90-00907b2b2ab6.png)

**Comment by oncletom** [comment]
Moisson_n_eur, via @odtvince et http://www.cnrtl.fr/definition/moissonneur.

Ajouté comme suggestions : https://www.transifex.com/etalab/udata/translate/#fr/javascript/59929099?qt=moissoneur

**Comment by noirbizarre** [comment]
L'issue devrait être sur opendatateam/udata
