### ISSUE TITLE
La souris "saute" sur le bouton join

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/udata-gouvfr#209]
Sur la page organisation, lorsque je passe ma souris sur le bouton join, le pointeur saute.

[souris_saute.zip](https://github.com/etalab/udata-gouvfr/files/1190113/souris_saute.zip)

(github ne prend pas les fichiers webm, je l'ai donc mis dans un zip …)

**Comment by oncletom** [comment]
![kapture 2017-08-01 at 10 47 02](https://user-images.githubusercontent.com/138627/28819635-c482722c-76a6-11e7-83b7-5308ecae41f8.gif)

@l-vincent-l J'arrive à reproduire sous Chrome, Firefox et Safari.

J'ai l'impression que c'est lié aux infobulles.
Mais j'ai aussi l'impression que c'est résolu dans la version suivante (`udata@1.1`). Si t'essaies sur https://next.data.gouv.fr/fr/organizations/etalab/, le problème ne devrait plus se manifester.

Tu confirmes ?

Merci d'avoir pris le temps de signaler l'erreur :-)

**Comment by l-vincent-l** [comment]
Oui, ça fonctionne dans la prochaine version, je clos l'erreur.
