### ISSUE TITLE
API GEO

### ISSUE THREAD

**Issue by thomas-bhn** [etalab/udata-gouvfr#217]
Bonjour,

Pouvez-vous ajouter un limite de résultat pour l'API GEO 
exemple :
```
data : {
  nom : $('#searchCity').val(),
  maxResult: 15
},
```
https://api.gouv.fr/api/api-geo.html

**Comment by jdesboeufs** [comment]
Bonjour,

Votre question concerne un autre projet.
Aussi je vous suggère d'aller voter pour cette issue : 
https://github.com/etalab/api-communes/issues/79

Merci pour votre retour.
