### ISSUE TITLE
[Couverture Spatiale] Comment remplir ce champ ?

### ISSUE THREAD

**Issue by jerbou** [etalab/udata-gouvfr#231]
Bonjour,

Pour un utilisateur novice, la saisie du champ couverture spatiale n'est pas aisée.
De ce que j'ai compris, elle s'appuie sur le champ d'aprés Granularité spatiale, une fois choisie cette granularité, l'autocomplétion nous inviterai à saisie un vocabulaire controlée.
Dans mon cas présent, je souhaite saisir la bourgogne-franche-comté (id=27), mais l'autocomplétion ne semble pas fonctionner pour cette granulo (région).

On aurait tendance à présenter le champ granulo avant la couverture spatial, qui permettra de mieux comprendre ce qui est attendu en saisie.

D'avance Merci,
![couv_spat](https://user-images.githubusercontent.com/7600693/32956768-0e2e390c-cbba-11e7-8650-7faff043e0b1.jpg)

**Comment by jerbou** [comment]
Mauvaise catégorie pour l'issue, désolé 👎

**Comment by noirbizarre** [comment]
Bonjour,

Je n'ai pas eu le temps de répondre, mais il y avait effectivement un bug que je viens de corriger.

Vous devriez trouver votre résultat maintenant.

Votre navigateur ayant probablement gardé la réponse précédante en cache pour 24h, vous pouvez essayer d'allonger la longueur de votre requête pour le forcer à récupérer de nouveaux résultats (Essayez de saisir `bourgogne-fra` ou encore `Bourgogne` avec une majuscule ou bien son code nuts2 `FR26`).
