### ISSUE TITLE
passage de doc.data.gouv.fr à data.gouv.fr

### ISSUE THREAD

**Issue by romtal** [etalab/udata-gouvfr#242]
Il est impossible de passer de www.doc.data.gouv.fr à www.data.gouv.fr en cliquant en haut à gauche de la page sur le logo data.gouv.fr qui renvoie vers www.doc.data.gouv.fr

**Comment by noirbizarre** [comment]
Déplacée sur le bon dépôt: https://github.com/etalab/doc.data.gouv.fr/issues/7

(par ailleurs, pour communiquer, c'est doc.data.gouv.fr et non www.doc.data.gouv.fr :wink:)

**Comment by romtal** [comment]
C'est noté ;)
