### ISSUE TITLE
License page: point to an external md content

### ISSUE THREAD

**Issue by abulte** [etalab/udata-gouvfr#250]
In order to be able to modify the licenses page without releasing a new `udata-gouvfr` version, we should make the licenses page content an external markdown content, just like we did for terms and conditions (https://raw.githubusercontent.com/etalab/data.gouv.fr/master/CGU.md).

**Comment by abulte** [comment]
How do we manage attachments with this solution?

**Comment by abulte** [comment]
@etalab/datagouv WDYT?

**Comment by davidbgk** [comment]
Can't it be part of https://github.com/etalab/doc.data.gouv.fr ?

**Comment by noirbizarre** [comment]
@davidbgk This solution was proposed but it has already been written in the law that it should be on www.data.gouv.fr :cry: 

Maybe a redirect could do the trick.

If not, the terms page was a first pass but I believe the behavior can be extracted and reused by other pages.

For the attachments, markdown provide all that's necessary (just link to the content). Then we have 3 solutions:
- link to external existing attachment (can be uploaded on any other site, doc.data.gouv.fr etalab.gouv.fr...)
- join the attachement as static asset and link it
- provide a view to do so (but I think this is a little bit of over ingeneering)
