### ISSUE TITLE
Download "tag.csv"

### ISSUE THREAD

**Issue by ThomasMenant** [etalab/udata-gouvfr#300]
Faire apparaitre le lien de téléchargement des tags : https://www.data.gouv.fr/fr/tags.csv?

![image](https://user-images.githubusercontent.com/16664528/39044655-1d1e622a-4491-11e8-93a7-b0ddf2a796ff.png)

**Comment by abulte** [comment]
Done https://www.data.gouv.fr/fr/datasets/catalogue-des-donnees-de-data-gouv-fr/#resource-648b51aa-6d29-46d6-bf12-ffc63303674b 💥
