### ISSUE TITLE
Moteur de recherche - Les suggestions sont difficilement cliquables

### ISSUE THREAD

**Issue by mdamien** [etalab/udata-gouvfr#308]
Dans les résultats suggérés, seule la partie verte sur cette capture d'écran permet d'accéder au résultat. Si l'on clique sur la partie rouge, la boite de dialogue disparait sans enregistrer le choix.

![image](https://user-images.githubusercontent.com/1469823/40541943-3bdaff9a-601e-11e8-9a49-ddcade687732.png)

En éspérant que la capture d'écran est assez claire.

A priori le bug est dans udata mais j'ai la flemme de faire une PR pour ca: https://github.com/opendatateam/udata/blob/1214485fcf2bea645d73b83f53eac4b8759167ca/js/components/site-search.vue#L236

**Comment by noirbizarre** [comment]
Il semble que le bug vienne d'autre part, le rendu attendu et constaté (ce jour même) est le suivant:

### Firefox
![screenshot-www data gouv fr-2018-05-25-15-25-32](https://user-images.githubusercontent.com/15725/40546672-2dfc511e-6030-11e8-804e-730ff2822b36.png)


### Chrome/Chromium/Safari/Webkit
![screenshot-www data gouv fr-2018 05 25-15-26-07](https://user-images.githubusercontent.com/15725/40546646-1c07e036-6030-11e8-9f7a-8ce5d9badf3a.png)

Toute la zone est cliquable, pas uniquement le texte.

Quelle est votre navigateur et sa version ?

**Comment by mdamien** [comment]
Le rendu est mauvais sur ma carte d'écran car j'avais la souris sur le résultat (en hover).

Sinon, j'ai reproduit le bug sur Firefox et Chromium:

```
Firefox: 60.0.1 (64-bit)
Chromium: Version 66.0.3359.139 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
```

Mais la PR de @taniki a l'air niquel

**Comment by noirbizarre** [comment]
:+1:
