### ISSUE TITLE
Manual fix for missing user's discussions

### ISSUE THREAD

**Issue by abulte** [etalab/udata-gouvfr#314]
In order to fix https://sentry.data.gouv.fr/etalab/www-datagouvfr/issues/132742/

Maybe run this in production:

```
user = User(id='5432c1b188ee38108f64e607', first_name='DELETED', last_name='DELETED', email='5432c1b188ee38108f64e607@deleted')
user.save()
```

As for #313, this does not seem to need a permanent fix. Users should never be "really" deleted.

**Comment by noirbizarre** [comment]
Agreed :ok_hand:

**Comment by abulte** [comment]
Done in production, fixed.
