### ISSUE TITLE
quelle est la licence des fichiers fournis dans ce repo?

### ISSUE THREAD

**Issue by boyera** [etalab/udata-gouvfr#502]
Si le repo de udata est clair sur la licence sous laquelle le soft est fourni, je ne vois pas de fichier de licence pour celui-ci? je suis en particulier interessé par votre badge "producteur certifié" https://github.com/etalab/udata-gouvfr/blob/master/theme/img/certified-stamp.png et j'aimerais savoir s'il est libvre de droit ou s'il est reutilisable/modifiable et selon quelles conditions?
merci d'avance

**Comment by abulte** [comment]
La licence était un peu caché en effet (LGPL) https://github.com/etalab/udata-gouvfr/blob/master/setup.py#L74. Je l'ai rajoutée au dépôt via https://github.com/etalab/udata-gouvfr/blob/master/LICENSE.
